apiVersion: v1
kind: Service
metadata:
  name: api-pharma
  namespace: cp-gt
  labels:
    app: cp-pharma
spec:
  type: ClusterIP
  selector:
    app: cp-pharma
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
status:
  loadBalancer: {}
